language: go
go:
- tip
script:
- go build
deploy:
  provider: releases
  api_key:
    secure: rJdFuF92KcKUbo6pQvhR7rOB5BCBgVCD+pQ3+Ft9uOCOc7rb3L0zWzMpgbtQfxdvhA8EU3/EbszgvWscM+ryEsvlc+r0V6dY76DPC3f/Ai1rnGtkNNE+dyRr9VOhwYEn2umI1OBxNLeqbBd5RXnfZnObUkFkUG1fCmKM8zo1K8kaixlF4uh0jnJfBDHkE02W5x0AlJ5PU3QjJvHMSpXGTfo8HAZ4q5oxtXQ7WIhlZC2LjUCE/3vlZTQIlhHEz2Tg4g5Duxj65mOPeBJknA/6+w7O6nzO48mxkDTkT/haCHGJtI8veeqdDfgUk32wilvGQbvyvdyfA6VHROkXsj2B4UAxDjY/aaALd+bcZsWOn32GHC7KzEKX1TUvDMKNjZ41UJ3RsvzT9NsoNCFpetnLTIywUveR0u3Jz7m0UZ6XvfMKy1tWXpiCSOw+crzrvED8Um/HzIbauc/MgEeAflnN4UkgMoQkq0RRD9oYGqy1JWYDyGOdxJuPgaZCvhAtUJ8aHvhz5M2BW09mjwBBjHvJc5QAObOcuMfHukami9NejwHEl5EItDR00otaNOLjXC9GQRPKRiCkb2vkv/OWRVhZjNEK3fAykOMHrAKMN9X2rmHbv77XAXcKz8BlgB+x+v0OUTKiO7AiuPXNWi4rFGkvsRqDY7bi/oJHgzbYEbyMj6o=
  file: envtool
  skip_cleanup: true
  on:
    tags: true
